# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0q1nhfmcgfa5w515hknwidvc6sv1i0chgkr7a09li7mg1rv29jsq";
    aarch64-linux = "1m8ddr4l4gg6qg3zfw6mjwr0xh901xlpvqg65b2ilgdasy0846a8";
    x86_64-darwin = "1rl332pdiff42882a7h0qcaiwlpvh9jr6gwpbil0573a3zj510nr";
    aarch64-darwin = "11zyjg8nvi6zp99wy7xywy3slyb81xdiwy7g89svcxqzdlwna7bx";
  };

  urlMap = {
    x86_64-linux = "https://github.com/pipekit/cli/releases/download/v7.4.0/cli_7.4.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/pipekit/cli/releases/download/v7.4.0/cli_7.4.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/pipekit/cli/releases/download/v7.4.0/cli_7.4.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/pipekit/cli/releases/download/v7.4.0/cli_7.4.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "pipekit";
  version = "7.4.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./pipekit $out/bin/pipekit
  '';

  meta = {
    description = "Pipekit CLI";
    homepage = "https://pipekit.io/";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
