# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1jb62bz81dnd0adwbhzkqq7d90ryq1cz5bnl7gd5n33hsl5annl6";
    aarch64-linux = "1a0j196ha6xvihcdyhsl1vgl1aa1l99pdi9fsdq6yi23fd2k1zk5";
    x86_64-darwin = "0i66q6j1hdzcggqazy1jsgrhziiap1nn2jmnnqpmydi39s1drq7y";
    aarch64-darwin = "1pxx2jylnz1543qngapnvna3v70zsc1883r3cm7q41xcbncg5yh5";
  };

  urlMap = {
    x86_64-linux = "https://github.com/pipekit/cli/releases/download/v6.66.4/cli_6.66.4_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/pipekit/cli/releases/download/v6.66.4/cli_6.66.4_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/pipekit/cli/releases/download/v6.66.4/cli_6.66.4_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/pipekit/cli/releases/download/v6.66.4/cli_6.66.4_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "pipekit";
  version = "6.66.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./pipekit $out/bin/pipekit
  '';

  meta = {
    description = "Pipekit CLI";
    homepage = "https://pipekit.io/";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
