# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1i7jz2bgzzv3k4r0y2s6hr4235mfnimxrmi61r151s5phfdxhjzp";
    aarch64-linux = "1h2mknwiaadvp1klhk70qn74zk21nl7q7mh5zvqa0d4n1f08f63a";
    x86_64-darwin = "16gxhabgbnnkw5ghahsq6danj3z6g7pxagvl6mjw1siidzqqd9di";
    aarch64-darwin = "03wd7c1bs27a5pgm952f5x886yxj6yximdqq00dcyx0pm2hwp4pr";
  };

  urlMap = {
    x86_64-linux = "https://github.com/pipekit/cli/releases/download/v7.4.2/cli_7.4.2_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/pipekit/cli/releases/download/v7.4.2/cli_7.4.2_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/pipekit/cli/releases/download/v7.4.2/cli_7.4.2_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/pipekit/cli/releases/download/v7.4.2/cli_7.4.2_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "pipekit";
  version = "7.4.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./pipekit $out/bin/pipekit
  '';

  meta = {
    description = "Pipekit CLI";
    homepage = "https://pipekit.io/";
    license = lib.licenses.unfree;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
